apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/run-level: "1" 
  name: "{{flexran_du_ns}}"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vran-operators 
  namespace: "{{flexran_du_ns}}"
spec:
  targetNamespaces:
  - "{{flexran_du_ns}}"
{% if fec_use_subscription %}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sriov-fec-subscription
  namespace: "{{flexran_du_ns}}"
spec:
  channel: stable
  name: sriov-fec
  source: certified-operators
  sourceNamespace: openshift-marketplace
{% else %}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: intel-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: {{fec_index_url}}
  publisher: Intel
  displayName: Intel operators(Local)
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sriov-fec-subscription
  namespace: "{{flexran_du_ns}}"
spec:
  channel: stable
  name: sriov-fec
  source: intel-operators
  sourceNamespace: openshift-marketplace
{% endif %}
