apiVersion: performance.openshift.io/v2 #v1alpha1
kind: PerformanceProfile
metadata:
  name: cnv-sriov-profile
  namespace: openshift-performance-addon
spec:
  cpu:
    isolated: "{{ du_isolated_cpus.stdout | trim }}"
    reserved: "{{ du_reserved_cpus.results[0].stdout }}"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
