apiVersion: performance.openshift.io/v2 #v1alpha1
kind: PerformanceProfile
metadata:
  name: cnv-sriov-profile
  namespace: openshift-performance-addon
spec:
  cpu:
    isolated: "{{ du_isolated_cpus.stdout | trim }}"
    reserved: "{{ du_reserved_cpus.results[0].stdout }}"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 32
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  additionalKernelArgs:
{% if secure_boot %}
  - vfio_pci.enable_sriov=1
  - vfio_pci.disable_idle_d3=1
{% endif %}
  - processor.max_cstate=1
  - intel_idle.max_cstate=0
  - idle=poll
  - selinux=0
  - enforcing=0
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - kthread_cpus=0
  - irqaffinity=0

