apiVersion: v1 
kind: Pod 
metadata:
  name: flexran-du
  namespace: "{{flexran_du_ns}}"
  annotations:
    k8s.v1.cni.cncf.io/networks: >
      [
         {
           "name": "sriov-vlan10",
           "mac": "00:11:22:33:00:00"
         },
         {
           "name": "sriov-vlan20",
           "mac": "00:11:22:33:00:10"
         }
      ]
spec:
  restartPolicy: Never
  containers:
  - name: flexran-du 
    image: "{{ansible_default_ipv4.address}}:5000/flexran:{{flexran_version}}"
    imagePullPolicy: Always 
    command:
      - sleep
      - infinity 
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /sys
      name: sys
    - name: varrun
      mountPath: /var/run/dpdk
    - name: dev
      mountPath: /dev
    resources:
      limits:
        hugepages-1Gi: 16Gi
        memory: 16Gi
        cpu: 32
        intel.com/intel_fec_acc100: '1'
      requests:
        hugepages-1Gi: 16Gi
        memory: 16Gi
        cpu: 32 
        intel.com/intel_fec_acc100: '1'
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: sys
    hostPath:
      path: /sys
  - name: varrun
    emptyDir: {}
  - name: dev
    hostPath:
      path: /dev
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
