- name: install tmux
  yum:
    name: tmux
    state: present

- name: install linuxptp 
  yum:
    name: linuxptp
    state: latest

- name: replace priority setting in ptp4l.conf
  lineinfile:
    path: /etc/ptp4l.conf
    regexp: '^priority1(\s+).*'
    line: "priority1\t\t127"

- name: replace OPTIONS in /etc/sysconfig/phc2sys
  lineinfile:
    path: /etc/sysconfig/phc2sys
    regexp: '^OPTIONS=.*'
    line: OPTIONS="{{'-a -r -r -m' if ru_is_gm is defined and ru_is_gm else '-a -r -m' }}"

- name: replace OPTIONS in /etc/sysconfig/ptp4l
  lineinfile:
    path: /etc/sysconfig/ptp4l
    regexp: '^OPTIONS=.*'
    line: OPTIONS="-f /etc/ptp4l.conf -i {{ru_ptp_int}} -2 -m"

- name: stop chronyd
  systemd:
    name: chronyd
    state: stopped
  when: ru_is_gm is not defined or not ru_is_gm

- name: Enable ptp4l.service
  systemd:
    name: ptp4l.service
    enabled: yes
  become: yes

- name: Start ptp4l.service
  systemd:
    name: ptp4l.service
    state: restarted
  become: yes

- name: Enable phc2sys.service
  systemd:
    name: phc2sys.service
    enabled: yes
  become: yes

- name: Start phc2sys.service
  systemd:
    name: phc2sys.service
    state: restarted
  become: yes

- name: create {{test_run_dir}} 
  file:
    path: "{{test_run_dir}}"
    state: directory
    mode: 0755
  become: yes

- name: copy scripts to {{test_run_dir}} 
  copy:
    src: "{{role_path}}/../lib/scripts/"
    dest: "{{test_run_dir}}/"
  become: yes


- name: create {{test_run_dir}}/ru_sriov.sh
  template:
    src: ru_sriov.sh
    dest: "{{test_run_dir}}/ru_sriov.sh"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: execute {{test_run_dir}}/ru_sriov.sh
  shell: "{{test_run_dir}}/ru_sriov.sh"
  args:
    chdir: "{{test_run_dir}}"
  register: result
  become: yes

- set_fact:
    oru_sriov_str: "{{ result.stdout }}"

- name: create {{test_run_dir}}/ru_start.sh
  template:
    src: ru_start.sh
    dest: "{{test_run_dir}}/ru_start.sh"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: execute {{test_run_dir}}/ru_start.sh
  shell: "{{test_run_dir}}/ru_start.sh"
  args:
    chdir: "{{test_run_dir}}"
  become: yes

