- name: Create {{test_run_dir}} if not exists
  file:
    path: "{{test_run_dir}}"
    state: directory
    mode: 0755
  become: yes

- name: Retrieve current secrets
  shell: oc get secret/pull-secret -n openshift-config --template={% raw %}'{{index .data ".dockerconfigjson" | base64decode}}'{% endraw %} > {{test_run_dir}}/pull_secret.json

- name: Add secret for each registry
  shell: oc registry login --skip-check --registry="{{registry.url}}" --auth-basic="{{registry.user}}:{{registry.pass}}" --to={{test_run_dir}}/pull_secret.json
  loop: "{{registry_secrets}}"
  loop_control:
    loop_var: registry

- name: Update pull secrets
  shell: oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson={{test_run_dir}}/pull_secret.json

