---
- set_fact:
    cert_data: "{{ lookup('file', '/opt/registry/certs/cert.crt') }}"

- name: create the configmap registry-cas
  k8s:
    state: present
    namespace: openshift-config
    definition: "{{ lookup('template', 'cm_cert.yml') }}"


#- name: remove existing configmap registry-cas
#  k8s:
#   api_version: v1
#   state: absent
#   kind: ConfigMap
#   namespace: openshift-config
#   name: registry-cas
#
#- name: add configmap registry-cas
#  shell: oc create configmap registry-cas -n openshift-config --from-file={{ansible_default_ipv4.address}}..5000=/opt/registry/certs/cert.crt


- name: patch image.config.openshift.io/cluster
  k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: Image
      metadata:
        name: cluster
        namespace: default
      spec:
        additionalTrustedCA:
          name: registry-cas

- name: wait for 120 second to get cert effective
  pause: seconds=120
