---
- name: Label baremetal worker nodes as worker-cnf
  k8s:
    kind: Node
    name: "{{ hostvars[item].hostname }}"
    resource_definition:
      metadata:
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
  with_items: "{{ groups['baremetal_workers'] }}"
 
- set_fact:
    package_name: "sriov-network-operator"

- import_tasks: "{{ role_path }}/../lib/tasks/get-channel.yml"

- name: Apply the SRIOV Subscription config
  k8s:
    state: present
    definition: "{{ lookup('template', 'sub-sriov.yml') }}"
  register: sub_version

- set_fact:
    namespace: openshift-sriov-network-operator

- import_tasks: "{{ role_path }}/../lib/tasks/wait-csv.yml"
#- import_tasks: "{{ role_path }}/../lib/tasks/wait-csv-perf.yml"

- name: Execute SRIOV interface PCI command on baremetal worker over SSH
  shell: "{{ role_path }}/../lib/scripts/exec_over_ssh.sh {{ hostvars[item].hostname }} 'ethtool -i {{ du_sriov_int }} ' | awk '/bus-info:/{print $NF;}'"
  register: du_sriov_int_pci
  with_items: "{{ groups['baremetal_workers'] }}"

- name: Log all_cpus
  debug: 
   msg: "du_sriov_int_pci: {{du_sriov_int_pci.results[0].stdout}}"

- name: Apply the SRIOV NIC Policy config
  k8s:
    state: present
    definition: "{{ lookup('template', 'sriov-nic-policy.yml') }}"
  register: result

- name: Apply the SRIOV VLAN Network configs
  k8s:
    state: present
    definition: "{{ lookup('template', 'sriov-network.yml') }}"
  register: result_2

- pause:
    seconds: 60
  when: (result.changed or result_2.changed)

- name: Wait for VF creation
  shell: |
    "{{ role_path }}/../lib/scripts/exec_over_ssh.sh" "{{ hostvars[item].hostname }}" "ip link show {{ du_sriov_int }} | egrep '^\s+vf\s'"
  register: vf_status
  retries: 30
  delay: 5
  with_items: "{{ groups['baremetal_workers'] }}"
  until:
    - (vf_status.stdout | length > 0)
  when: (result.changed or result_2.changed)
