apiVersion: v1
kind: Pod
metadata:
  name: flexran-du
  namespace: "{{flexran_du_ns}}"
spec:
  restartPolicy: Never
  containers:
    - name: flexran-du
      image: {{ flexran_image | default(ansible_default_ipv4.address+':5000/flexran:'+flexran_version|string) }}
      imagePullPolicy: Always
{% if secure_boot_static_token %}
      env:
      - name: VFIO_TOKEN
        valueFrom:
          secretKeyRef:
            name: vfio-token
            key: VFIO_TOKEN
{% endif %}
      command:
        - sleep
        - infinity
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /dev/hugepages
          name: hugepage
        - mountPath: /sys
          name: sys
        - name: varrun
          mountPath: /var/run/dpdk
        - name: dev
          mountPath: /dev
      resources:
        limits:
          hugepages-1Gi: 20Gi 
          memory: 20Gi
          cpu: 32
          intel.com/intel_fec_acc100: '1'
        requests:
          hugepages-1Gi: 20Gi
          memory: 20Gi
          cpu: 32
          intel.com/intel_fec_acc100: '1'
  volumes:
    - name: hugepage
      emptyDir:
        medium: HugePages
    - name: sys
      hostPath:
        path: /sys
    - name: varrun
      emptyDir: {}
    - name: dev
      hostPath:
        path: /dev
  nodeSelector:
    node-role.kubernetes.io/{{ node_role }}: ''
