---
all:
  vars:
    test_run_dir: /opt/ru_scripts
    du_ptp_int: ens3f0
    du_sriov_int: ens1f0
    du_fec_pci: "0000:b5:00.0"
    flexran_du_ns: default
    flexran_version: 21.03
    ru_sriov_int: ens6f0
    ru_ptp_int: ens3f0
    ru_is_gm: true
    flexran_dir: /opt/flexran
    orancfg_dir: /opt/flexran/bin/nr5g/gnb/l1/orancfg
    orancfgs:
      - sub3_mu0_20mhz_4x4
      - sub3_mu0_10mhz_4x4 
    node_role: worker-cnf
    timercfgs:
      - clxsp_mu0_20mhz_4x4_hton.cfg
    secure_boot: false
    fec_use_subscription: false 
    fec_index_url: "quay.io/intel-operator/n3000-operators-index@sha256:3f27e4a7bfbd238f39212b4f766c0ac3d525ede916b283b67a92788a2fba7872"
    registry_secrets:
      - url: quay.io/intel-operator
        user: jianzzha
        pass: 2FQwY1lNiy/84n0YbRE6E9hY+gXpHi1QGz1dPuVzsQVUpYGI45vqXNwTBmikAOuz
  hosts:
    tgen:
      ansible_connection: local
  children:
    jumphosts: ## Only one jumphost
      hosts:
        jumphost:
          ansible_connection: local
    baremetal_workers:
      hosts:
        worker1:
          hostname: worker1

